@hostname = localhost
@port = 8080
# @port = 9999
@host = http://{{hostname}}:{{port}}

POST {{host}}/pessoas
Content-Type: application/json

{
  "apelido" : "vqwCSkgJBBdyawdHXawds",
  "nome" : "Minnie Roberstson",
  "nascimento" : "1990-12-06",
  "stack" : [
    "Java",
    "Scala"
  ]
}

###

GET {{host}}/pessoas/bd4f7e83-b703-47d7-8131-bdf7a698dca9

###

GET {{host}}/pessoas?t=java

###

GET {{host}}/contagem-pessoas
